### ISSUE TITLE
TypeError: read_original_data() takes exactly 3 arguments (1given)

### ISSUE THREAD

**Issue by cannguyen275** [elleros/spoofed-speech-detection#1]
Hi,
I got problem with this line:
x = vad.read_original_data(folder+f_name)
the error is:
Traceback (most recent call last):
  File "/home/thangtran/Can/spoofdetection/testsource.py", line 68, in <module>
    x = vad.read_original_data(folder+f_name)
TypeError: read_original_data() takes exactly 3 arguments (1 given)

I try a lot but I can't fix it. Do you have any solution for this problem?
Thank a lot

**Comment by elleros** [comment]
You are probably using the latest version of bob.bio.spear (3.2.1?), while I used the 2.04. In the version you are using [read_original_data](https://www.idiap.ch/software/bob/docs/bob/bob.bio.base/stable/implementation.html?highlight=read_original_data) requires 3 parameters. Click on the link for details.

**Comment by sduchh** [comment]
@cannguyen275 Have you solved this problem?

**Comment by cannguyen275** [comment]
@sduchh Yes, I've replaced this function with my new function.
Add this function to your code.
```python
def read(filename):
  """Read video.FrameContainer containing preprocessed frames"""

  fileName, fileExtension = os.path.splitext(filename)
  wav_filename = filename
  rate, data = scipy.io.wavfile.read(str(wav_filename)) # the data is read in its native format
  if data.dtype =='int16':
    data = numpy.cast['float'](data)
  return [rate,data]
```
Then use ```x = read(folder+f_name)``` instead of ```read_original_data```

**Comment by sduchh** [comment]
@cannguyen275 It's great! Thanks very much!
